### ISSUE TITLE
mvn package fails

### ISSUE THREAD

**Issue by happy-hadooper** [happy-hadooper/Hyrax#3]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ parse ---
Downloading: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom
Downloaded: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom (0 B at 0.0 KB/sec)
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  com.twitter:chill_2.10:0.5.0 requires scala version: 2.10.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] /home/dmitry/Hyrax/src/main/java:-1: info: compiling
[INFO] /home/dmitry/Hyrax/src/main/scala:-1: info: compiling
[INFO] Compiling 10 source files to /home/dmitry/Hyrax/target/classes at 1469107451114
[INFO] Picked up _JAVA_OPTIONS: -Xmx2048m -XX:MaxPermSize=512m 
[WARNING] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[ERROR] /home/dmitry/Hyrax/src/main/scala/ua/hyrax/parse/util/Container.scala:3: error: not found: object parse
[ERROR] import parse.Const
[ERROR]        ^
[ERROR] /home/dmitry/Hyrax/src/main/scala/ua/hyrax/parse/util/Container.scala:4: error: not found: object parse
[ERROR] import parse.model.{Log, State}
[ERROR]        ^
[ERROR] /home/dmitry/Hyrax/src/main/scala/ua/hyrax/parse/util/Parse.scala:6: error: not found: object parse
[ERROR] import parse.model.Log
[ERROR]        ^
[WARNING] /home/dmitry/Hyrax/src/main/scala/ua/hyrax/parse/util/Parse.scala:27: warning: This catches all Throwables. If this is really intended, use `case _ : Throwable` to clear this warning.
[WARNING]       case _ => println("Some other shit happened")
[WARNING]            ^
[ERROR] /home/dmitry/Hyrax/src/main/scala/ua/hyrax/parse/util/Print.scala:6: error: not found: object parse
[ERROR] import parse.model.Log
[ERROR]        ^
[WARNING] one warning found
[ERROR] four errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.461s
[INFO] Finished at: Thu Jul 21 16:24:13 EEST 2016
[INFO] Final Memory: 18M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project parse: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Devian-ua** [comment]
Fixed package names.
